format_version: 10
pipelines:
  code-pipeline-test:
    group: My-Pipelines
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-ae8f4c8:
        git: https://github.com/akarshInvent/gocd-test
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - code-stage-test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          install:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - install
                command: npm
                run_if: passed
